package lpp.parser;

public enum TokenType { // important: SKIP, IDENT, and NUM must have ordinals 1, 2 and 3 
  EOF, SKIP, IDENT, NUM, STRING, PRINT, LET, PLUS, TIMES, EQ, ASSIGN, OPEN_PAR,
  CLOSE_PAR, OPEN_PAIR, CLOSE_PAIR, STMT_SEP, EXP_SEP, OPEN_BLOCK_OR_SET, CLOSE_BLOCK_OR_SET, MINUS, NOT, AND, CAT, DIM, UNION,
  INTERSECT, BOOL, IF, ELSE, FST, SND, WHILE, IN
}
